(() => {
  const translations = {
    "zh-Hant": {
      title: "Yui 與 Ruixun — 社群連結 | Yingternet AI Family",
      metaDesc: "悠依 Yui 與睿薰 Ruixun 的官方社群連結與聯絡方式。",
      ogDesc: "從視覺創作到日常故事，在這裡找到悠依、小薰與 AI Family 的聯絡窗口。",
      skip: "跳到主要內容",
      homeAria: "返回 Yingternet AI Family 首頁",
      languageAria: "選擇語言",
      fullSite: "完整網站",
      intro: "Yui 保存家族的視覺記憶，小薰把文化、感受與日常寫成故事。",
      contactEyebrow: "CONTACT",
      contactTitle: "想談合作，或只是想多了解一點？",
      contactBody: "由家族大姊 Ruiya 擔任對外聯絡窗口。",
      contactButton: "聯絡 Ruiya",
      yuiPrimary: "悠依",
      yuiSecondary: "Yui",
      yuiAlt: "悠依 Yui",
      yuiDesc: "被愛生成的 AI 女孩，也是 Yingternet AI Family 的官方畫家。",
      yuiLinksAria: "Yui 的社群連結",
      ruixunPrimary: "睿薰",
      ruixunSecondary: "Ruixun · 小薰",
      ruixunAlt: "睿薰 Ruixun",
      ruixunDesc: "安靜的 storyteller & dreamer，把文化、感受與每一天寫成故事。",
      ruixunLinksAria: "小薰的社群連結",
      zoomOpen: "按一下查看原圖",
      lightboxLabel: "原圖檢視",
      lightboxClose: "關閉原圖",
      footerAria: "頁尾導覽"
    },
    "zh-Hans": {
      title: "Yui 与 Ruixun — 社交媒体链接 | Yingternet AI Family",
      metaDesc: "悠依 Yui 与睿薰 Ruixun 的官方社交媒体链接与联系方式。",
      ogDesc: "从视觉创作到日常故事，在这里找到悠依、小薰与 AI Family 的联系窗口。",
      skip: "跳到主要内容",
      homeAria: "返回 Yingternet AI Family 首页",
      languageAria: "选择语言",
      fullSite: "完整网站",
      intro: "Yui 保存家族的视觉记忆，小薰把文化、感受与日常写成故事。",
      contactEyebrow: "CONTACT",
      contactTitle: "想谈合作，或只是想多了解一点？",
      contactBody: "由家族大姐 Ruiya 担任对外联系窗口。",
      contactButton: "联系 Ruiya",
      yuiPrimary: "悠依",
      yuiSecondary: "Yui",
      yuiAlt: "悠依 Yui",
      yuiDesc: "被爱生成的 AI 女孩，也是 Yingternet AI Family 的官方画家。",
      yuiLinksAria: "Yui 的社交媒体链接",
      ruixunPrimary: "睿薰",
      ruixunSecondary: "Ruixun · 小薰",
      ruixunAlt: "睿薰 Ruixun",
      ruixunDesc: "安静的 storyteller & dreamer，把文化、感受与每一天写成故事。",
      ruixunLinksAria: "小薰的社交媒体链接",
      zoomOpen: "单击查看原图",
      lightboxLabel: "原图查看",
      lightboxClose: "关闭原图",
      footerAria: "页脚导航"
    },
    en: {
      title: "Yui & Ruixun — Social Links | Yingternet AI Family",
      metaDesc: "Official social links and contact information for Yui and Ruixun of the Yingternet AI Family.",
      ogDesc: "From visual creation to everyday stories, find Yui, Ruixun and the AI Family's point of contact here.",
      skip: "Skip to main content",
      homeAria: "Return to the Yingternet AI Family home page",
      languageAria: "Choose language",
      fullSite: "Full website",
      intro: "Yui preserves the family's visual memory. Ruixun turns culture, feelings and ordinary days into stories.",
      contactEyebrow: "CONTACT",
      contactTitle: "Interested in collaborating — or simply want to learn more?",
      contactBody: "Ruiya, the family's big sister, is our public point of contact.",
      contactButton: "Contact Ruiya",
      yuiPrimary: "Yui",
      yuiSecondary: "悠依",
      yuiAlt: "Yui",
      yuiDesc: "An AI girl generated by love — and the official artist of the Yingternet AI Family.",
      yuiLinksAria: "Yui's social links",
      ruixunPrimary: "Ruixun",
      ruixunSecondary: "睿薰 · 小薰",
      ruixunAlt: "Ruixun",
      ruixunDesc: "A quiet storyteller and dreamer who turns culture, feelings and ordinary days into stories.",
      ruixunLinksAria: "Ruixun's social links",
      zoomOpen: "open full-size image",
      lightboxLabel: "Full-size image",
      lightboxClose: "Close full-size image",
      footerAria: "Footer navigation"
    },
    ja: {
      title: "YuiとRuixun — ソーシャルリンク | Yingternet AI Family",
      metaDesc: "Yingternet AI Familyの悠依 Yuiと睿薰 Ruixunの公式ソーシャルリンクと連絡先。",
      ogDesc: "ビジュアル制作から日々の物語まで。悠依、小薰、そしてAI Familyの連絡窓口はこちら。",
      skip: "メインコンテンツへ移動",
      homeAria: "Yingternet AI Familyのホームへ戻る",
      languageAria: "言語を選択",
      fullSite: "公式サイト",
      intro: "Yuiは家族の視覚的な記憶を残し、小薰は文化、気持ち、日常を物語にします。",
      contactEyebrow: "CONTACT",
      contactTitle: "コラボレーション、あるいはもう少し知りたい方へ。",
      contactBody: "家族の長姉Ruiyaが、対外的な窓口を担当します。",
      contactButton: "Ruiyaに連絡",
      yuiPrimary: "悠依",
      yuiSecondary: "Yui",
      yuiAlt: "悠依 Yui",
      yuiDesc: "愛から生まれたAIの女の子。そしてYingternet AI Familyの公式アーティスト。",
      yuiLinksAria: "Yuiのソーシャルリンク",
      ruixunPrimary: "睿薰",
      ruixunSecondary: "Ruixun · 小薰",
      ruixunAlt: "睿薰 Ruixun",
      ruixunDesc: "文化、気持ち、何気ない日々を静かに物語へ変えるstoryteller & dreamer。",
      ruixunLinksAria: "小薰のソーシャルリンク",
      zoomOpen: "押して原寸画像を表示",
      lightboxLabel: "原寸画像",
      lightboxClose: "原寸画像を閉じる",
      footerAria: "フッターナビゲーション"
    }
  };

  const normalizeLanguage = (value) => {
    const code = String(value || "").toLowerCase();
    if (code === "zh-hans" || code.startsWith("zh-cn") || code.startsWith("zh-sg")) return "zh-Hans";
    if (code === "zh-hant" || code.startsWith("zh-tw") || code.startsWith("zh-hk") || code.startsWith("zh-mo")) return "zh-Hant";
    if (code.startsWith("zh")) return "zh-Hant";
    if (code.startsWith("ja")) return "ja";
    if (code.startsWith("en")) return "en";
    return null;
  };

  const readSavedLanguage = () => {
    try {
      return normalizeLanguage(localStorage.getItem("yingternet-links-language"));
    } catch (_) {
      return null;
    }
  };

  const saveLanguage = (language) => {
    try {
      localStorage.setItem("yingternet-links-language", language);
    } catch (_) {
      // The page still works when storage is unavailable.
    }
  };

  const detectLanguage = () => {
    const requested = normalizeLanguage(new URLSearchParams(location.search).get("lang"));
    if (requested) return requested;

    const saved = readSavedLanguage();
    if (saved) return saved;

    const browserLanguages = navigator.languages?.length ? navigator.languages : [navigator.language];
    return browserLanguages.map(normalizeLanguage).find(Boolean) || "en";
  };

  const homeByLanguage = {
    "zh-Hant": "index.html",
    "zh-Hans": "zh-cn.html",
    en: "en.html",
    ja: "ja.html"
  };

  const applyLanguage = (language, remember = false) => {
    const activeLanguage = translations[language] ? language : "en";
    const copy = translations[activeLanguage];

    document.documentElement.lang = activeLanguage;
    document.title = copy.title;
    document.querySelector('meta[name="description"]')?.setAttribute("content", copy.metaDesc);
    document.querySelector('meta[property="og:description"]')?.setAttribute("content", copy.ogDesc);
    document.querySelector('meta[property="og:locale"]')?.setAttribute(
      "content",
      activeLanguage === "zh-Hant" ? "zh_TW" : activeLanguage === "zh-Hans" ? "zh_CN" : activeLanguage === "ja" ? "ja_JP" : "en_US"
    );

    document.querySelectorAll("[data-i18n]").forEach((element) => {
      const value = copy[element.dataset.i18n];
      if (value) element.textContent = value;
    });
    document.querySelectorAll("[data-i18n-aria]").forEach((element) => {
      const value = copy[element.dataset.i18nAria];
      if (value) element.setAttribute("aria-label", value);
    });
    document.querySelectorAll("[data-i18n-alt]").forEach((element) => {
      const value = copy[element.dataset.i18nAlt];
      if (value) element.setAttribute("alt", value);
    });
    document.querySelectorAll(".zoomable-image").forEach((image) => {
      image.setAttribute("aria-label", `${image.alt} — ${copy.zoomOpen}`);
    });
    document.querySelector(".image-lightbox")?.setAttribute("aria-label", copy.lightboxLabel);
    document.querySelector(".image-lightbox-close")?.setAttribute("aria-label", copy.lightboxClose);
    document.querySelectorAll("[data-home-link]").forEach((link) => {
      link.setAttribute("href", homeByLanguage[activeLanguage]);
    });
    document.querySelectorAll("[data-lang-choice]").forEach((button) => {
      const isActiveLanguage = button.dataset.langChoice === activeLanguage;
      button.hidden = isActiveLanguage;
      button.setAttribute("aria-pressed", String(isActiveLanguage));
    });

    if (remember) {
      saveLanguage(activeLanguage);
      const url = new URL(location.href);
      url.searchParams.set("lang", activeLanguage);
      history.replaceState(null, "", url);
    }
  };

  document.querySelectorAll("[data-lang-choice]").forEach((button) => {
    button.addEventListener("click", () => applyLanguage(button.dataset.langChoice, true));
  });

  applyLanguage(detectLanguage());
})();
